In [2]:
import numpy as np

In [6]:
import random

a = np.zeros((2,3))

for row in range(2):
    for col in range(3):
        a[row,col] = random.randint(0,20)
a

array([[ 5., 11., 10.],
       [20.,  6., 20.]])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
range(5)

range(0, 5)

In [9]:
np.arange(5) #ndarray의 원소 범위

array([0, 1, 2, 3, 4])

In [10]:
np.arange(3,6)

array([3, 4, 5])

In [12]:
a = np.arange(3,10,2)
type(a)

numpy.ndarray

In [13]:
np.arange(1,10,0.8)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2, 9. , 9.8])

In [14]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a.shape

(12,)

In [16]:
a.reshape(3,4) #3행 4열

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a.shape #원본은 그대로 냅두고 reshape은 새로 메몸리공간에 저장함.

(12,)

In [18]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
# 0~9 구간을 7개 수를 일정한 간격으로 추출하려면?, linearly spaced values
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.random.random()

0.9325762877675793

In [22]:
np.random.random(3)

array([0.13407989, 0.52929328, 0.38508842])

In [23]:
np.random.random((3,3))  

array([[0.06749992, 0.6135059 , 0.09283003],
       [0.09991772, 0.94090137, 0.09437249],
       [0.09644899, 0.592268  , 0.08511034]])

# 문제1,
ndarray원소가 16개인 1차원 배열 생성<br>
4 * 4 변환

In [24]:
#1답
np.random.random(16).reshape((4,4))

array([[0.53748196, 0.20701979, 0.4673226 , 0.97734028],
       [0.06906225, 0.02136369, 0.07336882, 0.57132482],
       [0.29280089, 0.59050231, 0.97373216, 0.63850349],
       [0.53951361, 0.16092337, 0.13584673, 0.91186912]])

In [25]:
a.data  #a라는 배열이 저장된 메모리 주소 출력

In [29]:
b = a.reshape(-1,12)
b.data  #b의 메모리 주소 출력

In [32]:
a1 = a.flatten()
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
a1.data

In [36]:
a = np.arange(4)
a.data

In [41]:
a +[1,1,1,1]

array([1, 2, 3, 4])

In [37]:
a1 = a + 1
a1.data

In [40]:
a, a1

(array([0, 1, 2, 3]), array([1, 2, 3, 4]))

In [42]:
a

array([0, 1, 2, 3])

In [43]:
a*2

array([0, 2, 4, 6])

In [44]:
#Element-wise
a * np.sin(1.2)

array([0.        , 0.93203909, 1.86407817, 2.79611726])

In [45]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [46]:
np.sqrt(a) # universal function

array([0.        , 1.        , 1.41421356, 1.73205081])

In [47]:
np.array([1,2,3]) * np.array([3,4,5])

array([ 3,  8, 15])

In [50]:
a = np.arange(6).reshape(2,-1) #reshape으로 2행으로 다시 정렬하여 새로운 메모리공간에 저장
a

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
b = np.arange(6).reshape(3,-1)  #reshape으로 3행으로 다시 정렬하여 새로운 메모리공간에 저장
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [54]:
np.dot(a,b) #dot product(내적, Innger Product)

array([[10, 13],
       [28, 40]])

In [55]:
#dir(a)
a.dot(b)   # a, b

array([[10, 13],
       [28, 40]])

In [56]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [57]:
a + 1

array([1, 2, 3, 4, 5])

In [58]:
a

array([0, 1, 2, 3, 4])

In [60]:
a += 1
a

array([2, 3, 4, 5, 6])

In [61]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [62]:
a.sum()

10

In [66]:
a.max(), a.min(), a.mean(), a.std()  #mean:평균, std:표준편차

(4, 0, 2.0, 1.4142135623730951)

In [67]:
#평균(m)
#분산(Variance): 각 원소와 평균의 차이의 제곱, 이들을 모두 합산, 그 값을 원소의 갯수로 나눔
#표준편차(std) :분산의 제곱근

m = np.arange(5)
m.mean(),m.var(),m.std()

(2.0, 2.0, 1.4142135623730951)

In [69]:
a

array([0, 1, 2, 3, 4])

In [71]:
np.sqrt(np.mean(abs(a-a.mean())**2)),np.std(a)

(1.4142135623730951, 1.4142135623730951)

In [72]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [73]:
a[2],a[-1],a[0],a[-6]

(12, 15, 10, 10)

In [74]:
a[a.size-1]  #[a-1]과 같은 결과

15

In [75]:
a[[1,2,3]]

array([11, 12, 13])

In [76]:
a = np.arange(1,17).reshape(4,-1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [79]:
for e in a:
    for i in e:
        print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [ ]:
a[1][2], a[1,2],a[[1,2]]  #이 셋은 완전히 다른 결과

(7,
 7,
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [84]:
#fancy indexing: 인덱서 안에 정수나 불리언 배열을 사용하여 배열의 값을 추출해내는 방법
ba = np.array([True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False])
ba = ba.reshape(4,-1)
ba

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [85]:
a[ba]

array([1])

In [87]:
a<2  #정수형 배열

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [88]:
a[a<2]  #boolean 배열

array([1])

In [89]:
nums = [1,2,3,4,5]
nums[0:5]

[1, 2, 3, 4, 5]

In [90]:
nums[::2]

[1, 3, 5]

In [91]:
a[::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
nums=list(range(5))
nums

[0, 1, 2, 3, 4]

In [93]:
nums2= nums[:]
nums2

[0, 1, 2, 3, 4]

In [94]:
nums2[0] = 5

In [95]:
nums

[0, 1, 2, 3, 4]

In [96]:
nums2

[5, 1, 2, 3, 4]

In [97]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [102]:
A = np.arange(10,19).reshape(3,-1)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [103]:
np.apply_along_axis(np.max, axis=1,arr=A)

array([12, 15, 18])

In [104]:
odd_sum = 0

for e in A.flat:
    if e%2==1: odd_sum += e
print(f'홀수의 합={odd_sum}')

홀수의 합=56


In [105]:
A[A%2==1]

array([11, 13, 15, 17])

In [106]:
A[A%2==1].sum()

56

In [108]:
A.data

A1 = A.reshape(1,-1)
A1.data

In [112]:
A1.shape= (3,-1)
A1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [113]:
A1.data

# View, Copies

In [114]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [115]:
b = a

In [116]:
a[2] = 0

In [117]:
b

array([1, 2, 0, 4])

In [118]:
c = a[0:2]
c

array([1, 2])

In [120]:
a[0] = 5
c

array([5, 2])

In [2]:
#csv(Comma Separated Values)
#sample.csv
'''
id,value1,value2,value3
1,123,1.4,23
2,110,0.5,18
3,164,2.1,19
'''

'\nid,value1,value2,value3\n1,123,1.4,23\n2,110,0.5,18\n3,164,2.1,19\n'

In [1]:
np.genfromtxt('sample.csv',delimiter=',',names=True)

NameError: name 'np' is not defined