# Numpy delete

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr = np.delete(arr,2)
arr

In [2]:
arr = np.array(["Alice","Bob","Charlie","David","Eric"])
arr = np.delete(arr,[0,1,2])
print(arr)

['David' 'Eric']


In [6]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr = np.delete(arr,[0,3],axis=1)  #[0,3] 두 컬럼을 삭제 ,axis=1:첫번째 행
print(arr)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [9]:
arr = np.array([1,1,1,1,2,3,4])
arr = np.delete(arr, np.where(arr ==1))
print(arr)

[2 3 4]


In [11]:
def delete_1(row):
    B = np.arange(16).reshape(4,-1)
    B = np.delete(B,row,axis=0)
    print(B)

In [ ]:
def delete_2(2):
    B = np.arange(16).reshape(4,-1)
    B = np.delete(B,row,axis=0)
    print(B)

In [14]:
delete_1(2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]]


# 문제1,.성적관리 프로그램(ndarray(NUMPY) CRUD 실습)
   - 5의 학생 성적(학생의 이름 번호)
   - 3과목(5*3 2차원 배열)
   - 3개의 배열 존재: 1차원 배열 2개, 2차원 배열 1개
   - 목록(s),추가(a),검색(번호로검색,f),수정(u),삭제(d),종료(x)
   - 성적 입력시 : 변호 이름을 먼저 받고, 3 과목 성적을 입력 받아서 저장
   - np.where(stid == 15) <-- 15인 원소의 인덱스 리턴
   - 삭제할 때는 '학생정보 삭제','과목삭제' 중 택 1 하도록 작성
   - names, stid, subjects, socres(2차원)
   - 파일에 저장하는 시기: 추가, 수정
   - 파일에서 로드하는 시기: 리스트, 검색
  

In [15]:
import numpy as np

In [16]:
names = np.array(['scott','jone','lora','blake','andy'])
subjects = np.array(['Java','Spring','Python'])
stid = np.array([11,12,13,14,15])
scores = np.zeros((5,3))

Name: pandas
Version: 1.4.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: c:\users\201-20\anaconda3\lib\site-packages
Requires: pytz, numpy, python-dateutil
Required-by: xarray, statsmodels, seaborn, hvplot, holoviews, datashader
