# Pandas 
- Series :표 한개의 컬럼을 표현(index, values)<br>
  표의  1차원 자료구조, ndarray + label(index)
- DataFrame<br>
  Series 다수 개를 포함하여 표를 표현한 자료구조

In [1]:
!pip show pandas

Name: pandas
Version: 1.4.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: c:\users\201-20\anaconda3\lib\site-packages
Requires: pytz, python-dateutil, numpy
Required-by: xarray, statsmodels, seaborn, hvplot, holoviews, datashader


In [2]:
import pandas as pd
import numpy as np

In [3]:
s = pd.Series([12,-4,7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [5]:
s = pd.Series([12,-4,7,9], index=['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

In [6]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
s.values

array([12, -4,  7,  9], dtype=int64)

In [8]:
type(s.values)

numpy.ndarray

In [9]:
s.values[s<0]

array([-4], dtype=int64)

In [10]:
tmp = s.values[s<0]
type(tmp)
tmp[0]

-4

In [11]:
s<0

a    False
b     True
c    False
d    False
dtype: bool

In [12]:
type(s<0)

pandas.core.series.Series

In [14]:
s

a    12
b    -4
c     7
d     9
dtype: int64

In [18]:
s[0]    #12
s[[0,1]]
s[s>0]
s[[False,True,False,False]]
type(s[[False,True,False,False]])  #Series 객체
s[[False,True,False,False]][0]   #Scala 값

s[0:2]

s['a']   #Scala
s[['a','b']]  #Series

a    12
b    -4
dtype: int64

In [19]:
s[0] = 100
s

a    100
b     -4
c      7
d      9
dtype: int64

In [21]:
s[['a','b']]
s

a    100
b     -4
c      7
d      9
dtype: int64

In [22]:
s = pd.Series([12,-4,7,9],index=['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

In [23]:
s2 = pd.Series(s)
s2

a    12
b    -4
c     7
d     9
dtype: int64

In [24]:
s2[0],s[0]


(12, 12)

In [25]:
s2[0] = -4
s2,s

(a   -4
 b   -4
 c    7
 d    9
 dtype: int64,
 a   -4
 b   -4
 c    7
 d    9
 dtype: int64)

In [26]:
s[s>0]

c    7
d    9
dtype: int64

In [35]:
nums = [12,-4,7,9]
s = pd.Series(nums)
s[1] = 4 # 음수를 양수로 바꾸기.
s
nums
s2 = pd.Series(s)
s2[0] = 100
s, s2, nums

(0    100
 1      4
 2      7
 3      9
 dtype: int64,
 0    100
 1      4
 2      7
 3      9
 dtype: int64,
 [12, -4, 7, 9])

In [37]:
s3 = s
s3

0    100
1      4
2      7
3      9
dtype: int64

In [38]:
s3[0] = 0
s,s2,s3 #같은 참조, 같은 뷰

(0    0
 1    4
 2    7
 3    9
 dtype: int64,
 0    0
 1    4
 2    7
 3    9
 dtype: int64,
 0    0
 1    4
 2    7
 3    9
 dtype: int64)

# 개념 1
- Indexer (loc[],iloc[])
- loc[] : labels, boolean
- iloc[] : position integer, boolean

In [40]:
s.index=['a','b','c','d']

In [44]:
# loc[] : labels,Boolean
s.loc['a']
s.loc[['a','b']]
s.loc[[True,False,False,False]]
s.loc[s>5][1]  #Seires, 두번째 값 추출

9

In [46]:
# iloc[] : Position integer, Boolean
s.iloc[0]
s.iloc[[0,1]]
s.iloc[[True,False,False,False]]
# s.iloc[s>5]   #ValueError
s.iloc[(s>5).to_list()]
s.iloc[(s>5).to_numpy()]

c    7
d    9
dtype: int64

In [47]:
type(s.values)  # numpy.ndarray
s.values
s.to_numpy()
s.to_list()

[0, 4, 7, 9]

In [48]:
arr = np.arange(5)
type(arr)
arr/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [49]:
s = pd.Series(arr*2)
s

0    0
1    2
2    4
3    6
4    8
dtype: int32

In [50]:
s/2

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [52]:
#에러는 나지 않지만 딕셔너리는 키가 중복되면 중복 출력이 안됨.
#기존에 입력된 값은 저장되지 않고 최근에 입력된 값이 메모리에 값이 대입되기 때문.
s = pd.Series({'a':1,'b':2,'b':3,'c':4,'c':5})
s

a    1
b    3
c    5
dtype: int64

In [53]:
#list는 중복된 키값 출력
s = pd.Series([1,2,3,4,5],index=['a','b','b','c','c'])
s

a    1
b    2
b    3
c    4
c    5
dtype: int64

In [54]:
#중복되지 않게 값을 가져오는 방법
s.unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [55]:
len(s)  #5
s.value_counts()

1    1
2    1
3    1
4    1
5    1
dtype: int64

In [56]:
'h' in 'hello'

True

In [57]:
s.isin([2,3])

a    False
b     True
b     True
c    False
c    False
dtype: bool

In [58]:
s2 = pd.Series([5,-3,np.NaN,14]) #NaN :Not a Number
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [60]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [61]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [62]:
np.mean(s2[s2.notnull()])

5.333333333333333

In [63]:
np.mean(s2[s2.notnull()])

5.333333333333333