# Merge
p.196,181

In [1]:
import numpy as np
import pandas as pd

In [2]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [3]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'color': ['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [4]:
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [5]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [6]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [7]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [8]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [9]:
pd.merge(frame1,frame2,on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [13]:
frame2.columns = ['sid','brand']  
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [14]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')

id  color brand_x     sid brand_y
0    ball  white     OMG    ball     ABC
1  pencil    red     ABC  pencil     OMG
2  pencil    red     ABC  pencil     POD
3     pen    red     ABC     pen     POD

In [16]:
frame2.columns = ['id','brand']
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [20]:
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [21]:
pd.merge(frame1,frame2,on='id',how='left')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [22]:
pd.merge(frame1,frame2,on='id',how='right')

id  color brand_x brand_y
0  pencil    red     ABC     OMG
1  pencil    red     ABC     POD
2    ball  white     OMG     ABC
3     pen    red     ABC     POD

# Merging on an Index
p.202,187

In [23]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [24]:
frame1.join(frame2)  #컬럼명이 달라서 에러남

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [26]:
frame2.columns = ['brand2','id2'] #join() 전에 frame2의 컬렴명을 재정의.
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

cf)<br>
outer join<br>
left outer join<br>
right outer join<br>
fuu outer join

In [37]:
#문제1
#분기:1~4
#팀1,팀2:무작위 정수 4개
sales1 = no.random(1,10,4)
df1 = pd.DataFrame({'분기':[1,2,3,4],'팀1':sales1})
df1

NameError: name 'no' is not defined

# Concatenating
p.203,188<br>
Another type of data combination is referred to as concatenation.

In [27]:
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [30]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

With the pandas library and its data structures like series and dataframe, having 
labeled axes allows you to further generalize the concatenation of arrays. The concat()
function is provided by pandas for this kind of operation

In [31]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

1    0.456292
2    0.993909
3    0.095433
4    0.721597
dtype: float64

In [32]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.280907
6    0.406994
7    0.095078
8    0.399887
dtype: float64

In [35]:
pd.concat([ser1,ser2])

1    0.456292
2    0.993909
3    0.095433
4    0.721597
5    0.259330
6    0.871377
7    0.023675
8    0.861542
dtype: float64